[package]
name = "lang"
version = "0.1.0"
authors = ["FelixMo42 <felix@tacocat.com>"]
edition = "2018"

[dependencies]
tblit = { git="https://github.com/FelixMo42/tblit" }
log = "0.4.14"
simplelog = "0.10.0"
